# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vsrmmt123
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-new-serv-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: deployLmdaWithApiGwLogging

provider:
  name: aws
  runtime: nodejs20.x
  logs:
    restApi: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: user/home
          method: get
